# Generated by Django 5.1.3 on 2026-03-17 10:06

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Allowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("amount", "Amount"), ("percentage", "Percentage")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Contract Name", max_length=255)),
                (
                    "description",
                    models.CharField(help_text="Description", max_length=255),
                ),
                (
                    "duration_month",
                    models.DurationField(help_text="Duration in months", max_length=20),
                ),
                ("is_permanent", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("amount", "Amount"), ("percentage", "Percentage")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(help_text="Leave Name", max_length=255)),
                (
                    "description",
                    models.CharField(help_text="Description", max_length=255),
                ),
                (
                    "duration",
                    models.DurationField(help_text="Duration in Days", max_length=20),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.ForeignKey(
                        help_text="Department Name",
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payroll", models.IntegerField(help_text="Payroll no", unique=True)),
                ("name", models.CharField(help_text="Employee Name", max_length=255)),
                (
                    "contact_email",
                    models.EmailField(
                        help_text="Email address", max_length=255, unique=True
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        help_text="format: 07xxxxx",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^07\\d{8}$", message="invalid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "nok_Name",
                    models.CharField(help_text="Next Of kin Name", max_length=255),
                ),
                (
                    "nok_phone_number",
                    models.CharField(
                        help_text="Next Of kin Phone Number",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^07\\d{8}$", message="invalid phone number"
                            )
                        ],
                    ),
                ),
                (
                    "nok_relationship",
                    models.CharField(help_text="Relationship", max_length=255),
                ),
                (
                    "designation",
                    models.CharField(help_text="Designation", max_length=255),
                ),
                ("is_HOD", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contract_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HumanResource.contracttype",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HumanResource.department",
                    ),
                ),
                (
                    "applicable_leave_type",
                    models.ManyToManyField(blank=True, to="HumanResource.leavetype"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowances",
                    models.ManyToManyField(blank=True, to="HumanResource.allowance"),
                ),
                (
                    "deductions",
                    models.ManyToManyField(blank=True, to="HumanResource.deduction"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HumanResource.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedSalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_processed", models.DateField(default=datetime.date.today)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="salary_pdfs/"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HumanResource.employee",
                    ),
                ),
                (
                    "salary_structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HumanResource.salarystructure",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "salary_structure", "date_processed")},
            },
        ),
    ]
