# Generated by Django 5.1.3 on 2026-04-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Finance", "0004_statementreport_statementline"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statementreport",
            old_name="generated_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="statementreport",
            name="supplier",
        ),
        migrations.AlterField(
            model_name="statementreport",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statementreport",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
