# Generated by Django 6.0.3 on 2026-03-12 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Client's Name", max_length=120, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address", max_length=254, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="format: 07xxxxx",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^07\\d{8}$", message="invalid phone number"
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("symbol", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("days", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Port Name", max_length=120, unique=True
                    ),
                ),
                ("country", models.CharField(help_text="country Name", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Salesrep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Sales Rep Name", max_length=120, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Sales Rep Email address", max_length=254, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="format: 07xxxxx",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^07\\d{8}$", message="invalid phone number"
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Supplier Name", max_length=120, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Supplier Email address", max_length=254, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="format: 07xxxxx",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^07\\d{8}$", message="invalid phone number"
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientMasterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterData.client",
                    ),
                ),
                (
                    "Currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterData.currency",
                    ),
                ),
                (
                    "PaymentTerm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterData.paymentterm",
                    ),
                ),
                (
                    "Salesrep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterData.salesrep",
                    ),
                ),
            ],
        ),
    ]
