# Generated by Django 5.1.3 on 2026-04-05 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MasterData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(help_text="Bank Name", max_length=120)),
                ("branch", models.CharField(help_text="Branch Name", max_length=120)),
                (
                    "account_number",
                    models.CharField(
                        help_text="Bank Account Number",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d+$", message="Account number must be numeric"
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Currency for the account",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MasterData.currency",
                    ),
                ),
            ],
        ),
    ]
