# Generated by Django 5.1.3 on 2026-04-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MasterData", "0002_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="reference",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
