# Generated by Django 6.0.3 on 2026-03-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IT", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfig",
            name="purpose",
            field=models.CharField(
                choices=[("payroll", "Payroll System"), ("ticket", "Ticket System")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailconfig",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="emailconfig",
            unique_together={("purpose", "is_active")},
        ),
    ]
